yarnPath: .yarn/releases/yarn-3.0.1.cjs

packageExtensions:
  '@chakra-ui/accordion@*':
    peerDependencies:
      'framer-motion': '3.x || 4.x'
  '@chakra-ui/skeleton@*':
    peerDependencies:
      '@chakra-ui/theme': '>=1.0.0'
      '@emotion/react': '^11.0.0'
      '@emotion/styled': '^11.0.0'
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependencies:
      'typescript': '*'
  '@graphql-codegen/cli@*':
    peerDependencies:
      'typescript': '*'
  '@xstate/inspect@*':
    peerDependenciesMeta:
      ws:
        optional: true
  '@chakra-ui/switch@*':
    peerDependencies:
      'framer-motion': '3.x || 4.x'
  'graphql-config@*':
    peerDependencies:
      'typescript': '*'
  'react-dev-utils@*':
    peerDependencies:
      'typescript': '*'
      'webpack': '*'
