name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      browser:
        description: Cypress browser to use

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.2.0

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn graphql-codegen && yarn tsc

      - name: Jest tests
        run: yarn jest --ci

      - name: Run Cypress
        uses: replayio/action-cypress@v0.1.4
        with:
          command: npm run e2e:server -- -- --
          browser: "Replay Firefox"
          apiKey: ${{ secrets.CYPRESS_REPLAY_API_KEY }}
          public: true
          issue-number: ${{ github.event.pull_request.number }}
          upload-all: true

      - run: npx @replayio/replay ls
        if: ${{ always() }}
        shell: bash 
